In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame()

In [4]:
df.head(5)

Empty DataFrame
Columns: []
Index: []

In [5]:
dataset_max_size = 10000

In [6]:
df['Age(Y)'] = np.random.randint(0,100, dataset_max_size)

In [7]:
df['BMI(kg/m2)'] = np.random.uniform(0, 70, dataset_max_size)

In [8]:
df

      Age(Y)  BMI(kg/m2)
0         56    3.289128
1          8   42.027462
2         64   37.710206
3         49   69.746457
4          7   28.109789
...      ...         ...
9995      37   51.402417
9996      48   52.771672
9997      74   13.974619
9998      14   49.306361
9999      16   43.060576

[10000 rows x 2 columns]

In [9]:
df['BMIStatus'] = df['BMI(kg/m2)'].apply(lambda x: "Under-weight" if x <= 18.5 else "Normal" if x >= 18.5 and x <= 24.9 else "Over-weight" if x >= 25 and x <= 29.9 else "Moderate-Obese" if x >=30 and x <= 34.9 else "Severely-Obese" if x>= 35 and x < 39.9 else "Morbidly-Obese")

In [10]:
# 0 => Male and 1 => Female

In [11]:
df['Gender'] = np.random.choice([0, 1], size=dataset_max_size, p=[0.6, 0.4])

In [12]:
# 0 => No and 1 => Yes

In [13]:
df['InheritStatus'] = np.random.choice([0, 1], size=dataset_max_size, p=[0.8, 0.2])

In [14]:
df.head(5)

   Age(Y)  BMI(kg/m2)       BMIStatus  Gender  InheritStatus
0      56    3.289128    Under-weight       1              0
1       8   42.027462  Morbidly-Obese       1              0
2      64   37.710206  Severely-Obese       0              0
3      49   69.746457  Morbidly-Obese       0              0
4       7   28.109789     Over-weight       1              0

In [15]:
df['HbA1c(%)'] =  np.random.uniform(0, 15, dataset_max_size)

In [16]:
df['HbA1cStatus'] = df['HbA1c(%)'].apply(lambda x: "Non-diabetes" if x<5.7 else "Prediabetes" if x >= 5.7 and x <= 6.4 else "Diabetes" )

In [17]:
df.sample(5)

,Age(Y),BMI(kg/m2),BMIStatus,Gender,InheritStatus,HbA1c(%),HbA1cStatus
3738,33,52.320728,Morbidly-Obese,1,0,11.689800,Diabetes
4112,3,46.569330,Morbidly-Obese,0,0,13.952134,Diabetes
9135,24,51.940770,Morbidly-Obese,0,0,14.151781,Diabetes
6322,28,51.384023,Morbidly-Obese,0,0,1.507101,Non-diabetes
5293,79,9.931238,Under-weight,0,0,6.160919,Prediabetes

In [18]:
# 0 => No Alzheimer's and 1 => Alzheimer's detected

In [19]:
df["Alzheimer's"] = np.random.choice([0, 1], size=dataset_max_size, p=[0.92, 0.08])

In [20]:
df

,Age(Y),BMI(kg/m2),BMIStatus,Gender,InheritStatus,HbA1c(%),HbA1cStatus,Alzheimer's
0,56,3.289128,Under-weight,1,0,12.977559,Diabetes,0
1,8,42.027462,Morbidly-Obese,1,0,14.251916,Diabetes,0
2,64,37.710206,Severely-Obese,0,0,1.832511,Non-diabetes,0
3,49,69.746457,Morbidly-Obese,0,0,12.779523,Diabetes,1
4,7,28.109789,Over-weight,1,0,7.163098,Diabetes,1
...,...,...,...,...,...,...,...,...
9995,37,51.402417,Morbidly-Obese,0,0,8.376825,Diabetes,0
9996,48,52.771672,Morbidly-Obese,0,0,1.829837,Non-diabetes,0
9997,74,13.974619,Under-weight,1,1,7.760063,Diabetes,0
9998,14,49.306361,Morbidly-Obese,0,0,0.752810,Non-diabetes,0
9999,16,43.060576,Morbidly-Obese,1,0,0.827048,Non-diabetes,0

In [21]:
# 0 => Non Smokers and 1 => Smokers

In [22]:
df["Smoking"] = np.random.choice([0, 1], size=dataset_max_size, p=[0.50, 0.50])

In [23]:
df['Cholestrol(mg/dL)'] = np.random.randint(150,300, dataset_max_size)

In [24]:
df['HDLCholestrol(mg/dL)'] = np.random.randint(40,100, dataset_max_size)

In [25]:
df['LDLCholestrol(mg/dL)'] = np.random.randint(50,250, dataset_max_size)

In [26]:
df.head(5)

,Age(Y),BMI(kg/m2),BMIStatus,Gender,InheritStatus,HbA1c(%),HbA1cStatus,Alzheimer's,Smoking,Cholestrol(mg/dL),HDLCholestrol(mg/dL),LDLCholestrol(mg/dL)
0,56,3.289128,Under-weight,1,0,12.977559,Diabetes,0,1,173,58,192
1,8,42.027462,Morbidly-Obese,1,0,14.251916,Diabetes,0,1,179,78,162
2,64,37.710206,Severely-Obese,0,0,1.832511,Non-diabetes,0,1,172,56,205
3,49,69.746457,Morbidly-Obese,0,0,12.779523,Diabetes,1,1,213,64,169
4,7,28.109789,Over-weight,1,0,7.163098,Diabetes,1,0,192,76,238

In [27]:
df['CholestrolStatus'] = df['Cholestrol(mg/dL)'].apply(lambda x: "Heart-Healthy" if x < 200 else 'At-Risk' if x >= 200 and x < 240 else "Dangerous")

In [28]:
df['LDLCholestrolStatus'] = df['LDLCholestrol(mg/dL)'].apply(lambda x: "Heart-Healthy" if x < 100 else 'At-Risk' if x >= 100 and x < 160 else "Dangerous")

In [29]:
def hdlcholestrol(row):
    hdl = row['HDLCholestrol(mg/dL)']
    gender = row['Gender']
    
    if gender == 0:
        if hdl >= 40 and hdl <60:
            return "At-Risk"
        elif hdl < 40:
            return "Dangerous"
        else:
            return "Heart-Healthy"
    else:
        if hdl >= 50 and hdl <60:
            return "At-Risk"
        elif hdl < 50:
            return "Dangerous"
        else:
            return "Heart-Healthy"

In [30]:
df['HDLCholestrolStatus'] = df.apply(hdlcholestrol, axis=1)

In [31]:
df[:15]

,Age(Y),BMI(kg/m2),BMIStatus,Gender,InheritStatus,HbA1c(%),HbA1cStatus,Alzheimer's,Smoking,Cholestrol(mg/dL),HDLCholestrol(mg/dL),LDLCholestrol(mg/dL),CholestrolStatus,LDLCholestrolStatus,HDLCholestrolStatus
0,56,3.289128,Under-weight,1,0,12.977559,Diabetes,0,1,173,58,192,Heart-Healthy,Dangerous,At-Risk
1,8,42.027462,Morbidly-Obese,1,0,14.251916,Diabetes,0,1,179,78,162,Heart-Healthy,Dangerous,Heart-Healthy
2,64,37.710206,Severely-Obese,0,0,1.832511,Non-diabetes,0,1,172,56,205,Heart-Healthy,Dangerous,At-Risk
3,49,69.746457,Morbidly-Obese,0,0,12.779523,Diabetes,1,1,213,64,169,At-Risk,Dangerous,Heart-Healthy
4,7,28.109789,Over-weight,1,0,7.163098,Diabetes,1,0,192,76,238,Heart-Healthy,Dangerous,Heart-Healthy
5,39,9.882324,Under-weight,0,0,2.703627,Non-diabetes,0,0,286,68,134,Dangerous,At-Risk,Heart-Healthy
6,55,51.489774,Morbidly-Obese,0,0,10.099819,Diabetes,1,0,281,90,66,Dangerous,Heart-Healthy,Heart-Healthy
7,73,29.820849,Over-weight,0,0,6.088747,Prediabetes,0,0,227,74,197,At-Risk,Dangerous,Heart-Healthy
8,77,59.443538,Morbidly-Obese,0,0,4.496486,Non-diabetes,0,1,171,84,234,Heart-Healthy,Dangerous,Heart-Healthy
9,85,13.535177,Under-weight,0,0,10.064862,Diabetes,0,1,201,43,149,At-Risk,At-Risk,At-Risk
10,75,35.708489,Severely-Obese,0,1,1.956248,Non-diabetes,0,0,167,97,213,Heart-Healthy,Dangerous,Heart-Healthy
11,1,37.712791,Severely-Obese,1,0,1.311105,Non-diabetes,0,1,241,72,109,Dangerous,At-Risk,Heart-Healthy
12,4,66.825467,Morbidly-Obese,1,0,0.842624,Non-diabetes,0,0,292,50,62,Dangerous,Heart-Healthy,At-Risk
13,49,12.183259,Under-weight,0,0,8.430119,Diabetes,0,0,295,90,187,Dangerous,Dangerous,Heart-Healthy
14,4,24.888736,Normal,1,0,10.651367,Diabetes,0,1,231,80,176,At-Risk,Dangerous,Heart-Healthy

In [32]:
df['RandomGlucose(mg/dL)'] = np.random.uniform(70, 400, dataset_max_size)

In [33]:
df['SugarBloodLevel'] = df['RandomGlucose(mg/dL)'].apply(lambda x: "Fasting" if x >= 70 and x < 100 else "Impaired-Tolerance" if x >= 100 and x < 140 else "Pre-Diabetes" if x >= 140 and x < 200 else "Diabetes")

In [34]:
df.head()

,Age(Y),BMI(kg/m2),BMIStatus,Gender,InheritStatus,HbA1c(%),HbA1cStatus,Alzheimer's,Smoking,Cholestrol(mg/dL),HDLCholestrol(mg/dL),LDLCholestrol(mg/dL),CholestrolStatus,LDLCholestrolStatus,HDLCholestrolStatus,RandomGlucose(mg/dL),SugarBloodLevel
0,56,3.289128,Under-weight,1,0,12.977559,Diabetes,0,1,173,58,192,Heart-Healthy,Dangerous,At-Risk,206.643879,Diabetes
1,8,42.027462,Morbidly-Obese,1,0,14.251916,Diabetes,0,1,179,78,162,Heart-Healthy,Dangerous,Heart-Healthy,325.359299,Diabetes
2,64,37.710206,Severely-Obese,0,0,1.832511,Non-diabetes,0,1,172,56,205,Heart-Healthy,Dangerous,At-Risk,159.881874,Pre-Diabetes
3,49,69.746457,Morbidly-Obese,0,0,12.779523,Diabetes,1,1,213,64,169,At-Risk,Dangerous,Heart-Healthy,150.961596,Pre-Diabetes
4,7,28.109789,Over-weight,1,0,7.163098,Diabetes,1,0,192,76,238,Heart-Healthy,Dangerous,Heart-Healthy,240.694213,Diabetes

In [35]:
df['DiabetesType'] = df.apply(lambda row: 'Type 1' if row['HbA1c(%)'] > 10 or row['RandomGlucose(mg/dL)'] > 200 else ('Type 2' if row['HbA1c(%)'] > 6.5 else 'None'), axis=1)

In [36]:
# 1 => 'Yes' and 0 => 'No'

In [37]:
df['InsulinUsage'] = df['DiabetesType'].apply(lambda x: 1 if x == 'Type 1' else 0)

In [38]:
df['Hypertension'] = df['CholestrolStatus'].apply(lambda x: 1 if x in ['Dangerous', 'At-Risk'] else 0)

In [39]:
df = df.sample(frac = 1)

In [40]:
df.shape

(10000, 20)

In [41]:
df.to_csv('DiabetesTestData.csv', index=False)

In [42]:
df[:100].to_csv('DiabetesTestData100.csv', index=False)